[workspace]
members = [
  "gateway",
  "auth-service",
  "chat-service",
  "voice-service",
  "presence-service",
  "signaling",
  "crates/common",
  "crates/api",
  "crates/events",
  "crates/files",
]
resolver = "2"


