bind_addr = "127.0.0.1:14702"
mongodb_uri = "mongodb://localhost:27017"
redis_uri = "redis://127.0.0.1:6379/"
rabbitmq_uri = "amqp://guest:guest@127.0.0.1:5672/%2f"
s3_endpoint = "http://127.0.0.1:9000"
s3_bucket = "rscord"
s3_access_key = "minioadmin"
s3_secret_key = "minioadmin"
jwt_secret = "dev_secret_change_me_in_production"
