# RSCORD Microservices Configuration

[infrastructure]
mongodb_uri = "mongodb://localhost:27017"
redis_url = "redis://localhost:6379"
rabbitmq_url = "amqp://localhost:5672"
minio_endpoint = "localhost:9000"
minio_access_key = "minioadmin"
minio_secret_key = "minioadmin"

[security]
jwt_secret = "your-super-secret-jwt-key-change-in-production"
password_salt_rounds = 12

[services]
# Gateway Configuration
gateway_host = "0.0.0.0"
gateway_port = 14700

# Auth Service
auth_host = "0.0.0.0"
auth_port = 14701

# Chat Service
chat_host = "0.0.0.0"
chat_port = 14703

# Voice Service
voice_host = "0.0.0.0"
voice_port = 14705

# Presence Service
presence_host = "0.0.0.0"
presence_port = 14706

[voice]
# WebRTC Configuration
stun_servers = ["stun:stun.l.google.com:19302", "stun:stun1.l.google.com:19302"]
# Add TURN servers for production
# turn_servers = ["turn:your-turn-server.com:3478"]
# turn_username = "username"
# turn_password = "password"

# LiveKit Configuration (if used)
livekit_url = "ws://localhost:7880"
livekit_api_key = "devkey"
livekit_api_secret = "devsecret"

[logging]
level = "info"
format = "pretty"

[cors]
allowed_origins = ["http://localhost:3000", "http://localhost:5173", "tauri://localhost", "http://5.35.83.143:14700"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["*"]

[database]
# MongoDB settings
connection_timeout = 30
max_pool_size = 100
min_pool_size = 5

# Redis settings
redis_pool_size = 20
redis_timeout = 5

[performance]
# Rate limiting
requests_per_minute = 1000
burst_size = 50

# WebSocket limits
max_connections_per_user = 5
message_size_limit = 65536

# File upload limits
max_file_size = "50MB"
allowed_file_types = ["image/png", "image/jpeg", "image/gif", "image/webp", "video/mp4", "audio/mpeg", "audio/wav"]

[development]
# Development-only settings
auto_reload = true
debug_mode = true
fake_email_service = true
